swagger: "2.0"
info:
  description: ""
  version: "0.0.1"
  title: "FedHipster"
  termsOfService: ""
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/"
tags:
- name: "api"
  description: "FedHipster API"
  externalDocs:
    description: "Find out more"
    url: "http://www.fedhipster.com"
schemes:
- "https"
- "http"
paths:
  /api/generate:
    post:
      tags:
        - "api"
      summary: "Generate application"
      description: "Generates a new application from posted config"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Generator config object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Config"
      responses:
        405:
          description: "Invalid input"
  /api/files/{folderId}/{fileId}:
    get:
      tags:
      - "api"
      summary: "Get file by ID"
      description: "Returns a generated zip file"
      produces:
      - "application/octet-stream"
      - "application/zip"
      parameters:
      - name: "folderId"
        in: "path"
        description: "ID of folder to return"
        required: true
        type: "string"
      - name: "fileId"
        in: "path"
        description: "ID of file to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Not found"
definitions:
  Config:
    type: "object"
    required:
    - "generator-jhipster"
    - "applicationType"
    properties:
      generator-jhipster:
        type: "object"
        properties:
          applicationType:
            type: "string"
            enum:
            - "monolith"
            - "microservice"
            - "gateway"
            - "uaa"
          gitCompany:
            type: "string"
            example: "Company"
          baseName:
            type: "string"
            example: "SampleApp"
          packageName:
            type: "string"
            example: "com.fedhipster"
          packageFolder:
            type: "string"
            example: "com.fedhipster"
          serverPort:
            type: "integer"
            format: "int64"
            example: "8080"
          serviceDiscoveryType:
            type: "boolean"
            default: false
          authenticationType:
            type: "string"
            enum:
            - "jwt"
            - "oauth2"
            - "session"
            - "uaa"
          uaaBaseName:
            type: "string"
            example: "../uaa"
          cacheProvider:
            type: "string"
            enum:
            - "ehcache"
            - "hazelcast"
            - "infinispan"
            - "no"
          enableHibernateCache:
            type: "boolean"
          websocket:
            type: "boolean"
            default: false
          databaseType:
            type: "string"
            enum:
            - "sql"
            - "mongodb"
            - "cassandra"
            - "couchbase"
            - "no"
            default: "sql"
          devDatabaseType:
            type: "string"
            enum:
            - "h2Disk"
            - "h2Memory"
            - "mysql"
            - "mariadb"
            - "postgresql"
            - "oracle"
            - "mssql"
            - "mongodb"
            - "cassandra"
            - "couchbase"
            - "no"
            default: "h2Disk"
          prodDatabaseType:
            type: "string"
            enum:
            - "mysql"
            - "mariadb"
            - "postgresql"
            - "oracle"
            - "mssql"
            - "mongodb"
            - "cassandra"
            - "couchbase"
            - "no"
            default: "postgresql"
          searchEngine:
            type: "boolean"
            default: false
          enableSwaggerCodegen:
            type: "boolean"
            default: false
          messageBroker:
            type: "boolean"
            default: false
          buildTool:
            type: "string"
            enum:
            - "maven"
            - "gradle"
            default: "maven"
          useSass:
            type: "boolean"
            default: false
          clientPackageManager:
            type: "string"
            enum:
            - "npm"
          testFrameworks:
            type: "array"
            items:
              type: "string"
              enum:
              - "gatling"
              - "cucumber"
              - "protractor"
          enableTranslation:
            type: "boolean"
          nativeLanguage:
            type: "string"
            enum:
            - "en"
            - "es"
          languages:
            type: "array"
            items:
              type: "string"
              enum:
              - "en"
              - "es"
          clientFramework:
            type: "string"
            enum:
            - "angularX"
            - "react"
          jhiPrefix:
            type: "string"
            example: "jhi"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"